bookwyrm/urls.py
""" url routing for the app and api """
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from bookwyrm import settings, views
from bookwyrm.utils import regex

USER_PATH = r"^user/(?P<username>%s)" % regex.USERNAME
LOCAL_USER_PATH = r"^user/(?P<username>%s)" % regex.LOCALNAME

status_types = [
    "status",
    "review",
    "reviewrating",
    "comment",
    "quotation",
    "boost",
    "generatednote",
]
STATUS_PATH = r"%s/(%s)/(?P<status_id>\d+)" % (USER_PATH, "|".join(status_types))

BOOK_PATH = r"^book/(?P<book_id>\d+)"

STREAMS = "|".join(s["key"] for s in settings.STREAMS)

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # federation endpoints
    re_path(r"^inbox/?$", views.Inbox.as_view()),
    re_path(r"%s/inbox/?$" % LOCAL_USER_PATH, views.Inbox.as_view()),
    re_path(r"%s/outbox/?$" % LOCAL_USER_PATH, views.Outbox.as_view()),
    re_path(r"^\.well-known/webfinger/?$", views.webfinger),
    re_path(r"^\.well-known/nodeinfo/?$", views.nodeinfo_pointer),
    re_path(r"^\.well-known/host-meta/?$", views.host_meta),
    re_path(r"^nodeinfo/2\.0/?$", views.nodeinfo),
    re_path(r"^api/v1/instance/?$", views.instance_info),
    re_path(r"^api/v1/instance/peers/?$", views.peers),
    # polling updates
    re_path("^api/updates/notifications/?$", views.get_notification_count),
    re_path("^api/updates/stream/(?P<stream>[a-z]+)/?$", views.get_unread_status_count),
    # authentication
    re_path(r"^login/?$", views.Login.as_view(), name="login"),
    re_path(r"^login/(?P<confirmed>confirmed)?$", views.Login.as_view(), name="login"),
    re_path(r"^register/?$", views.Register.as_view()),
    re_path(r"confirm-email/?$", views.ConfirmEmail.as_view(), name="confirm-email"),
    re_path(
        r"confirm-email/(?P<code>[A-Za-z0-9]+)/?$",
        views.ConfirmEmailCode.as_view(),
        name="confirm-email-code",
    ),
    re_path(r"resend-link", views.resend_link, name="resend-link"),
    re_path(r"^logout/?$", views.Logout.as_view(), name="logout"),
    re_path(
        r"^password-reset/?$",
        views.PasswordResetRequest.as_view(),
        name="password-reset",
    ),
    re_path(
        r"^password-reset/(?P<code>[A-Za-z0-9]+)/?$", views.PasswordReset.as_view()
    ),
    # admin
    re_path(r"^settings/site-settings/?$", views.Site.as_view(), name="settings-site"),
    re_path(
        r"^settings/announcements/?$",
        views.Announcements.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/?$",
        views.Announcement.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/delete/?$",
        views.delete_announcement,
        name="settings-announcements-delete",
    ),
    re_path(
        r"^settings/email-preview/?$",
        views.site.email_preview,
        name="settings-email-preview",
    ),
    re_path(
        r"^settings/users/?$", views.UserAdminList.as_view(), name="settings-users"
    ),
    re_path(
        r"^settings/users/(?P<user>\d+)/?$",
        views.UserAdmin.as_view(),
        name="settings-user",
    ),
    re_path(
        r"^settings/federation/?$",
        views.Federation.as_view(),
        name="settings-federation",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/?$",
        views.FederatedServer.as_view(),
        name="settings-federated-server",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/block?$",
        views.federation.block_server,
        name="settings-federated-server-block",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/unblock?$",
        views.federation.unblock_server,
        name="settings-federated-server-unblock",
    ),
    re_path(
        r"^settings/federation/add/?$",
        views.AddFederatedServer.as_view(),
        name="settings-add-federated-server",
    ),
    re_path(
        r"^settings/federation/import/?$",
        views.ImportServerBlocklist.as_view(),
        name="settings-import-blocklist",
    ),
    re_path(
        r"^settings/invites/?$", views.ManageInvites.as_view(), name="settings-invites"
    ),
    re_path(
        r"^settings/requests/?$",
        views.ManageInviteRequests.as_view(),
        name="settings-invite-requests",
    ),
    re_path(
        r"^settings/requests/ignore?$",
        views.ignore_invite_request,
        name="settings-invite-requests-ignore",
    ),
    re_path(
        r"^invite-request/?$", views.InviteRequest.as_view(), name="invite-request"
    ),
    re_path(r"^invite/(?P<code>[A-Za-z0-9]+)/?$", views.Invite.as_view()),
    # moderation
    re_path(r"^settings/reports/?$", views.Reports.as_view(), name="settings-reports"),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/?$",
        views.Report.as_view(),
        name="settings-report",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/suspend/?$",
        views.suspend_user,
        name="settings-report-suspend",
    ),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/resolve/?$",
        views.resolve_report,
        name="settings-report-resolve",
    ),
    re_path(r"^report/?$", views.make_report, name="report"),
    # landing pages
    re_path(r"^about/?$", views.About.as_view(), name="about"),
    path("", views.Home.as_view(), name="landing"),
    re_path(r"^discover/?$", views.Discover.as_view(), name="discover"),
    re_path(r"^notifications/?$", views.Notifications.as_view(), name="notifications"),
    re_path(
        r"^notifications/(?P<notification_type>mentions)/?$",
        views.Notifications.as_view(),
        name="notifications",
    ),
    re_path(r"^directory/?", views.Directory.as_view(), name="directory"),
    # Get started
    re_path(
        r"^get-started/profile/?$",
        views.GetStartedProfile.as_view(),
        name="get-started-profile",
    ),
    re_path(
        r"^get-started/books/?$",
        views.GetStartedBooks.as_view(),
        name="get-started-books",
    ),
    re_path(
        r"^get-started/users/?$",
        views.GetStartedUsers.as_view(),
        name="get-started-users",
    ),
    # feeds
    re_path(r"^(?P<tab>{:s})/?$".format(STREAMS), views.Feed.as_view()),
    re_path(
        r"^direct-messages/?$", views.DirectMessage.as_view(), name="direct-messages"
    ),
    re_path(
        r"^direct-messages/(?P<username>%s)?$" % regex.USERNAME,
        views.DirectMessage.as_view(),
        name="direct-messages-user",
    ),
    # search
    re_path(r"^search/?$", views.Search.as_view(), name="search"),
    # imports
    re_path(r"^import/?$", views.Import.as_view(), name="import"),
    re_path(r"^import/(\d+)/?$", views.ImportStatus.as_view(), name="import-status"),
    # users
    re_path(r"%s\.json$" % USER_PATH, views.User.as_view()),
    re_path(r"%s/?$" % USER_PATH, views.User.as_view(), name="user-feed"),
    re_path(r"%s/rss" % USER_PATH, views.rss_feed.RssFeed(), name="user-rss"),
    re_path(
        r"%s/followers(.json)?/?$" % USER_PATH,
        views.Followers.as_view(),
        name="user-followers",
    ),
    re_path(
        r"%s/following(.json)?/?$" % USER_PATH,
        views.Following.as_view(),
        name="user-following",
    ),
    # lists
    re_path(r"%s/lists/?$" % USER_PATH, views.UserLists.as_view(), name="user-lists"),
    re_path(r"^list/?$", views.Lists.as_view(), name="lists"),
    re_path(r"^list/saved/?$", views.SavedLists.as_view(), name="saved-lists"),
    re_path(r"^list/(?P<list_id>\d+)(.json)?/?$", views.List.as_view(), name="list"),
    re_path(r"^list/delete/(?P<list_id>\d+)/?$", views.delete_list, name="delete-list"),
    re_path(r"^list/add-book/?$", views.list.add_book, name="list-add-book"),
    re_path(
        r"^list/(?P<list_id>\d+)/remove/?$",
        views.list.remove_book,
        name="list-remove-book",
    ),
    re_path(
        r"^list-item/(?P<list_item_id>\d+)/set-position$",
        views.list.set_book_position,
        name="list-set-book-position",
    ),
    re_path(
        r"^list/(?P<list_id>\d+)/curate/?$", views.Curate.as_view(), name="list-curate"
    ),
    re_path(r"^save-list/(?P<list_id>\d+)/?$", views.save_list, name="list-save"),
    re_path(r"^unsave-list/(?P<list_id>\d+)/?$", views.unsave_list, name="list-unsave"),
    # User books
    re_path(r"%s/books/?$" % USER_PATH, views.Shelf.as_view(), name="user-shelves"),
    re_path(
        r"^%s/(helf|books)/(?P<shelf_identifier>[\w-]+)(.json)?/?$" % USER_PATH,
        views.Shelf.as_view(),
        name="shelf",
    ),
    re_path(
        r"^%s/(books|shelf)/(?P<shelf_identifier>[\w-]+)(.json)?/?$" % LOCAL_USER_PATH,
        views.Shelf.as_view(),
        name="shelf",
    ),
    re_path(r"^create-shelf/?$", views.create_shelf, name="shelf-create"),
    re_path(r"^delete-shelf/(?P<shelf_id>\d+)?$", views.delete_shelf),
    re_path(r"^shelve/?$", views.shelve),
    re_path(r"^unshelve/?$", views.unshelve),
    # goals
    re_path(
        r"%s/goal/(?P<year>\d{4})/?$" % USER_PATH,
        views.Goal.as_view(),
        name="user-goal",
    ),
    re_path(r"^hide-goal/?$", views.hide_goal, name="hide-goal"),
    # preferences
    re_path(r"^preferences/profile/?$", views.EditUser.as_view(), name="prefs-profile"),
    re_path(
        r"^preferences/password/?$",
        views.ChangePassword.as_view(),
        name="prefs-password",
    ),
    re_path(r"^preferences/delete/?$", views.DeleteUser.as_view(), name="prefs-delete"),
    re_path(r"^preferences/block/?$", views.Block.as_view(), name="prefs-block"),
    re_path(r"^block/(?P<user_id>\d+)/?$", views.Block.as_view()),
    re_path(r"^unblock/(?P<user_id>\d+)/?$", views.unblock),
    # statuses

celerywyrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from celerywyrm import settings

urlpatterns = [
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookwyrm/models/announcement.py
""" admin announcements """
from django.db import models
from django.db.models import Q
from django.utils import timezone

from .base_model import BookWyrmModel


class Announcement(BookWyrmModel):
    """The admin has something to say"""

    user = models.ForeignKey("User", on_delete=models.PROTECT)
    preview = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    event_date = models.DateTimeField(blank=True, null=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=True)

    @classmethod
    def active_announcements(cls):
        """announcements that should be displayed"""
        now = timezone.now()
        return cls.objects.filter(
            Q(start_date__isnull=True) | Q(start_date__lte=now),
            Q(end_date__isnull=True) | Q(end_date__gte=now),
            active=True,
        )

bookwyrm/models/attachment.py
""" media that is posted in the app """
from django.db import models

from bookwyrm import activitypub
from .activitypub_mixin import ActivitypubMixin
from .base_model import BookWyrmModel
from . import fields


class Attachment(ActivitypubMixin, BookWyrmModel):
    """an image (or, in the future, video etc) associated with a status"""

    status = models.ForeignKey(
        "Status", on_delete=models.CASCADE, related_name="attachments", null=True
    )
    reverse_unfurl = True

    class Meta:
        """one day we'll have other types of attachments besides images"""

        abstract = True


class Image(Attachment):
    """an image attachment"""

    image = fields.ImageField(
        upload_to="status/",
        null=True,
        blank=True,
        activitypub_field="url",
        alt_field="caption",
    )
    caption = fields.TextField(null=True, blank=True, activitypub_field="name")

    activity_serializer = activitypub.Document

bookwyrm/models/author.py
""" database schema for info about authors """
from django.contrib.postgres.indexes import GinIndex
from django.db import models

from bookwyrm import activitypub
from bookwyrm.settings import DOMAIN

from .book import BookDataModel
from . import fields


class Author(BookDataModel):
    """basic biographic info"""

    wikipedia_link = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    isni = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    viaf_id = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    gutenberg_id = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    # idk probably other keys would be useful here?
    born = fields.DateTimeField(blank=True, null=True)
    died = fields.DateTimeField(blank=True, null=True)
    name = fields.CharField(max_length=255, deduplication_field=True)
    aliases = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    bio = fields.HtmlField(null=True, blank=True)

    def get_remote_id(self):
        """editions and works both use "book" instead of model_name"""
        return "https://%s/author/%s" % (DOMAIN, self.id)

    activity_serializer = activitypub.Author

    class Meta:
        """sets up postgres GIN index field"""

        indexes = (GinIndex(fields=["search_vector"]),)

bookwyrm/models/federated_server.py
""" connections to external ActivityPub servers """
from urllib.parse import urlparse
from django.apps import apps
from django.db import models
from .base_model import BookWyrmModel

FederationStatus = models.TextChoices(
    "Status",
    [
        "federated",
        "blocked",
    ],
)


class FederatedServer(BookWyrmModel):
    """store which servers we federate with"""

    server_name = models.CharField(max_length=255, unique=True)
    status = models.CharField(
        max_length=255, default="federated", choices=FederationStatus.choices
    )
    # is it mastodon, bookwyrm, etc
    application_type = models.CharField(max_length=255, null=True, blank=True)
    application_version = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def block(self):
        """block a server"""
        self.status = "blocked"
        self.save()

        # deactivate all associated users
        self.user_set.filter(is_active=True).update(
            is_active=False, deactivation_reason="domain_block"
        )

        # check for related connectors
        if self.application_type == "bookwyrm":
            connector_model = apps.get_model("bookwyrm.Connector", require_ready=True)
            connector_model.objects.filter(
                identifier=self.server_name, active=True
            ).update(active=False, deactivation_reason="domain_block")

    def unblock(self):
        """unblock a server"""
        self.status = "federated"
        self.save()

        self.user_set.filter(deactivation_reason="domain_block").update(
            is_active=True, deactivation_reason=None
        )

        # check for related connectors
        if self.application_type == "bookwyrm":
            connector_model = apps.get_model("bookwyrm.Connector", require_ready=True)
            connector_model.objects.filter(
                identifier=self.server_name,
                active=False,
                deactivation_reason="domain_block",
            ).update(active=True, deactivation_reason=None)

    @classmethod
    def is_blocked(cls, url):
        """look up if a domain is blocked"""
        url = urlparse(url)
        domain = url.netloc
        return cls.objects.filter(server_name=domain, status="blocked").exists()

bookwyrm/models/report.py
""" flagged for moderation """
from django.apps import apps
from django.db import models
from django.db.models import F, Q
from .base_model import BookWyrmModel


class Report(BookWyrmModel):
    """reported status or user"""

    reporter = models.ForeignKey(
        "User", related_name="reporter", on_delete=models.PROTECT
    )
    note = models.TextField(null=True, blank=True)
    user = models.ForeignKey("User", on_delete=models.PROTECT)
    statuses = models.ManyToManyField("Status", blank=True)
    resolved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        """notify admins when a report is created"""
        super().save(*args, **kwargs)
        user_model = apps.get_model("bookwyrm.User", require_ready=True)
        # moderators and superusers should be notified
        admins = user_model.objects.filter(
            Q(user_permissions__name__in=["moderate_user", "moderate_post"])
            | Q(is_superuser=True)
        ).all()
        notification_model = apps.get_model("bookwyrm.Notification", require_ready=True)
        for admin in admins:
            notification_model.objects.create(
                user=admin,
                related_report=self,
                notification_type="REPORT",
            )

    class Meta:
        """don't let users report themselves"""

        constraints = [
            models.CheckConstraint(check=~Q(reporter=F("user")), name="self_report")
        ]
        ordering = ("-created_date",)


class ReportComment(BookWyrmModel):
    """updates on a report"""

    user = models.ForeignKey("User", on_delete=models.PROTECT)
    note = models.TextField()
    report = models.ForeignKey(Report, on_delete=models.PROTECT)

    class Meta:
        """sort comments"""

        ordering = ("-created_date",)

bookwyrm/templates/settings/announcement_form.html
{% extends 'components/inline_form.html' %}
{% load i18n %}

{% block header %}
{% if announcement %}
{% trans "Edit Announcement" %}
{% else %}
{% trans "Create Announcement" %}
{% endif %}
{% endblock %}

{% block form %}
{% csrf_token %}
<input type="hidden" name="user" value="{{ request.user.id }}">
<p>
    <label class="label" for="id_preview">Preview:</label>
    {{ form.preview }}
    {% for error in form.preview.errors %}
    <p class="help is-danger">{{ error | escape }}</p>
    {% endfor %}
</p>
<p>
    <label class="label" for="id_content">Content:</label>
    {{ form.content }}
    {% for error in form.content.errors %}
    <p class="help is-danger">{{ error | escape }}</p>
    {% endfor %}
</p>
<p>
    <label class="label" for="id_event_date">Event date:</label>
    <input type="date" name="event_date" value="{{ form.event_date.value|date:'Y-m-d' }}" class="input" id="id_event_date">
    {% for error in form.event_date.errors %}
    <p class="help is-danger">{{ error | escape }}</p>
    {% endfor %}
</p>
<hr aria-hidden="true">
<div class="columns">
    <div class="column">
        <p>
            <label class="label" for="id_start_date">Start date:</label>
            <input type="date" name="start_date" class="input" value="{{ form.start_date.value|date:'Y-m-d' }}" id="id_start_date">
            {% for error in form.start_date.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
        </p>
    </div>
    <div class="column">
        <p>
            <label class="label" for="id_end_date">End date:</label>
            <input type="date" name="end_date" class="input" id="id_end_date" value="{{ form.end_date.value|date:'Y-m-d' }}">
            {% for error in form.end_date.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
        </p>
    </div>
    <div class="column is-narrow">
        <p>
            <label class="label" for="id_active">Active:</label>
            {{ form.active }}
            {% for error in form.active.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
        </p>
    </div>
</div>

<div class="field has-addons">
    <div class="control">
        <button type="submit" class="button is-primary">{% trans "Save" %}</button>
    </div>
</div>
{% endblock %}

bookwyrm/templates/settings/edit_server.html
{% extends 'settings/admin_layout.html' %}
{% load i18n %}
{% block title %}{% trans "Add instance" %}{% endblock %}

{% block header %}
{% trans "Add instance" %}
<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to instance list" %}</a>
{% endblock %}

{% block panel %}

<div class="tabs">
    <ul>
        {% url 'settings-import-blocklist' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Import block list" %}</a>
        </li>
        {% url 'settings-add-federated-server' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Add instance" %}</a>
        </li>
    </ul>
</div>

<form method="POST" action="{% url 'settings-add-federated-server' %}">
    {% csrf_token %}
    <div class="columns">
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_server_name">{% trans "Instance:" %}</label>
                <input type="text" name="server_name" maxlength="255" class="input" required id="id_server_name" value="{{ form.server_name.value|default:'' }}" placeholder="domain.com">
                {% for error in form.server_name.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
            <div class="field">
                <label class="label" for="id_status">{% trans "Status:" %}</label>
                <div class="select">
                    <select name="status" class="" id="id_status">
                        <option value="federated" {% if form.status.value == "federated" %}selected=""{% endif %}>{% trans "Federated" %}</option>
                        <option value="blocked" {% if form.status.value == "blocked" or not form.status.value %}selected{% endif %}>{% trans "Blocked" %}</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_application_type">{% trans "Software:" %}</label>
                <input type="text" name="application_type" maxlength="255" class="input" id="id_application_type" value="{{ form.application_type.value|default:'' }}">
                {% for error in form.application_type.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
            <div class="field">
                <label class="label" for="id_application_version">{% trans "Version:" %}</label>
                <input type="text" name="application_version" maxlength="255" class="input" id="id_application_version" value="{{ form.application_version.value|default:'' }}">
                {% for error in form.application_version.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="field">
        <label class="label" for="id_notes">{% trans "Notes:" %}</label>
        <textarea name="notes" cols="None" rows="None" class="textarea" id="id_notes">{{ form.notes.value|default:'' }}</textarea>
    </div>

    <button type="submit" class="button is-primary">{% trans "Save" %}</button>
</form>

{% endblock %}

bookwyrm/templates/settings/federated_server.html
{% extends 'settings/admin_layout.html' %}
{% load i18n %}
{% load markdown %}

{% block title %}{{ server.server_name }}{% endblock %}

{% block header %}
{{ server.server_name }}

{% if server.status == "blocked" %}<span class="icon icon-x has-text-danger is-size-5" title="{% trans 'Blocked' %}"><span class="is-sr-only">{% trans "Blocked" %}</span></span>
{% endif %}

<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to list" %}</a>
{% endblock %}

{% block panel %}
<div class="columns">
    <section class="column is-half is-flex is-flex-direction-column">
        <h2 class="title is-4">{% trans "Details" %}</h2>
        <div class="box is-flex-grow-1 content">
            <dl>
                <div class="is-flex">
                    <dt>{% trans "Software:" %}</dt>
                    <dd>{{ server.application_type }}</dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Version:" %}</dt>
                    <dd>{{ server.application_version }}</dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Status:" %}</dt>
                    <dd>{{ server.status }}</dd>
                </div>
            </dl>
        </div>
    </section>

    <section class="column is-half is-flex is-flex-direction-column">
        <h2 class="title is-4">{% trans "Activity" %}</h2>
        <div class="box is-flex-grow-1 content">
            <dl>
                <div class="is-flex">
                    <dt>{% trans "Users:" %}</dt>
                    <dd>
                        {{ users.count }}
                        {% if server.user_set.count %}(<a href="{% url 'settings-users' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                    </dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Reports:" %}</dt>
                    <dd>
                        {{ reports.count }}
                        {% if reports.count %}(<a href="{% url 'settings-reports' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                    </dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Followed by us:" %}</dt>
                    <dd>
                        {{ followed_by_us.count }}
                    </dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Followed by them:" %}</dt>
                    <dd>
                        {{ followed_by_them.count }}
                    </dd>
                </div>
                <div class="is-flex">
                    <dt>{% trans "Blocked by us:" %}</dt>
                    <dd>
                        {{ blocked_by_us.count }}
                    </dd>
                </div>
            </dl>
        </div>
    </section>
</div>

<section class="block content">
    <header class="columns is-mobile">
        <div class="column">
            <h2 class="title is-4 mb-0">{% trans "Notes" %}</h2>
        </div>
        <div class="column is-narrow">
            {% trans "Edit" as button_text %}
            {% include 'snippets/toggle/open_button.html' with text=button_text icon_with_text="pencil" controls_text="edit_notes" %}
        </div>
    </header>
    {% if server.notes %}
    <div class="box" id="hide_edit_notes">{{ server.notes|to_markdown|safe }}</div>
    {% endif %}
    <form class="box is-hidden" method="POST" action="{% url 'settings-federated-server' server.id %}" id="edit_notes">
        {% csrf_token %}
        <p>
            <label class="is-sr-only" for="id_notes">Notes:</label>
            <textarea name="notes" cols="None" rows="None" class="textarea" id="id_notes">{{ server.notes|default:"" }}</textarea>
        </p>
        <button type="submit" class="button is-primary">{% trans "Save" %}</button>
        {% trans "Cancel" as button_text %}
        {% include 'snippets/toggle/close_button.html' with text=button_text controls_text="edit_notes" %}
    </form>
</section>

<section class="block content">
    <h2 class="title is-4">{% trans "Actions" %}</h2>
    {% if server.status != 'blocked' %}
    <form class="block" method="post" action="{% url 'settings-federated-server-block' server.id %}">
        {% csrf_token %}
        <button class="button is-danger">{% trans "Block" %}</button>
        <p class="help">{% trans "All users from this instance will be deactivated." %}</p>
    </form>
    {% else %}
    <form class="block" method="post" action="{% url 'settings-federated-server-unblock' server.id %}">
        {% csrf_token %}
        <button class="button">{% trans "Un-block" %}</button>
        <p class="help">{% trans "All users from this instance will be re-activated." %}</p>
    </form>
    {% endif %}
</section>

{% endblock %}

bookwyrm/templates/settings/user_admin_filters.html
{% extends 'snippets/filters_panel/filters_panel.html' %}

{% block filter_fields %}
{% include 'settings/server_filter.html' %}
{% include 'settings/username_filter.html' %}
{% endblock %}